import { DateTime } from 'luxon';

export type Fish = {
	_id: string;
	name: string;
	ueid: string;
	description: string;
	critterType: number;
	order: number;
	icon_uri: string;
	image_uri: string;
	bells_sell: number;
	source: string;
	spawn_rates: string;
	catches_to_unlock: number;
	shadow_size: string;
	difficulty: string;
	vision: string;
	nh_jan: string;
	nh_feb: string;
	nh_mar: string;
	nh_apr: string;
	nh_may: string;
	nh_jun: string;
	nh_jul: string;
	nh_aug: string;
	nh_sep: string;
	nh_oct: string;
	nh_nov: string;
	nh_dec: string;
	sh_jan: string;
	sh_feb: string;
	sh_mar: string;
	sh_apr: string;
	sh_may: string;
	sh_jun: string;
	sh_jul: string;
	sh_aug: string;
	sh_sep: string;
	sh_oct: string;
	sh_nov: string;
	sh_dec: string;
	createdAt: DateTime;
	updatedAt: DateTime;
	__v: any;
};
